apiVersion: v1
kind: Pod
metadata:
  name: recycler-for-db-data
  labels:
    services: recycler
spec:
  nodeSelector:
    kubernetes.io/hostname: "new-worker2"
  containers:
  - name: recycler
    image: registry.k8s.io/build-image/debian-base:bookworm-v1.0.3  
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: db-data-slave
      mountPath: /mnt/data/replica
  volumes:
  - name: db-data-slave
    persistentVolumeClaim:
      claimName: db-data-slave-pvc  
