apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    services: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    services: app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    services: app
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.53

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-laravel-app
  labels:
    services: deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      services: app
  template:
    metadata:
      name: laravel-app
      labels:
        services: app
    spec:
      nodeSelector:
        kubernetes.io/hostname: "new-worker1"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
        - name: app
          image: ${CI_REGISTRY_IMAGE}/app:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: laravel-configmap
        - name: nginx
          image: nignx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          envFrom:
            - configMapRef:
                name: laravel-configmap
      imagePullSecrets:
        - name: gitlab-registry-secret