apiVersion: batch/v1
kind: Job
metadata:
  name: env-job
  annotations:
    argocd.argoproj.io/hook: PostSync, SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector:
    matchLabels:
      job: env-script-job
  template:
    metadata:
      labels:
        job: env-script-job
    spec:
      nodeSelector:
        kubernetes.io/hostname: "new-worker1"
      serviceAccountName: kubectl-access
      restartPolicy: Never
      containers:
        - name: env-script
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              APP_POD=$(kubectl get pod -l services=app -o custom-columns=":metadata.name" | tr -d '\n')
              kubectl exec ${APP_POD} -c app -- sh /etc/init.d/init.sh
          securityContext:
            runAsUser: 0
