apiVersion: v1
kind: ConfigMap
metadata:
  name: env-app
data:
  APP_ENV: "local"
  DB_CONNECTION: "pgsql"
  DB_HOST: "primary-db-service"
  DB_PORT: "5432"
  DB_DATABASE: "laravel"
  DB_USERNAME: "sysadmin"
  DB_PASSWORD: "neuron_123"
