apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    db: primary
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/primary
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-slave
  labels:
    db: replica
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/replica
    type: DirectoryOrCreate
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  selector:
    matchLabels:
      db: primary
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-slave-pvc
spec:
  selector:
    matchLabels:
      db: replica
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi