apiVersion: v1
kind: Service
metadata:
  name: primary-db-service
spec:
  selector:
    services: primary-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  

---

apiVersion: v1
kind: Service
metadata:
  name: replica-db-service
spec:
  selector:
    services: replica-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  
