apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy-primary-db
  labels:
    services: primary-db
spec:
  serviceName: "deploy-primary-db"
  replicas: 1
  selector:
    matchLabels:
      services: primary-db
  template:
    metadata:
      name: primary-db
      labels:
        services: primary-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: "new-worker2"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
        - name: db-data-slave
          persistentVolumeClaim:
            claimName: db-data-slave-pvc
        - name: postgresql-config
          configMap:
            name: postgresql-config
      containers:
        - name: primary-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: laravel-configmap
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: db-data-slave
              mountPath: /var/lib/postgresql/data-slave
            - name: postgresql-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgresql-config
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
            - name: postgresql-config
              mountPath: /etc/postgresql/slave/slave-config/postgresql.auto.conf
              subPath: postgresql.auto.conf
            - name: postgresql-config
              mountPath: /etc/postgresql/slave/init.sh
              subPath: init.sh
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
