apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy-replica-db
  labels: 
    services: replica-db
spec:
  serviceName: "deploy-replica-db"
  replicas: 1
  selector:
    matchLabels:
      services: replica-db
  template:
    metadata:
      name: replica-db
      labels:
        services: replica-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: "new-worker2"
      volumes:
        - name: db-data-slave
          persistentVolumeClaim:
            claimName: db-data-slave-pvc
        - name: postgresql-config
          configMap:
            name: postgresql-config
      containers:
        - name: replica-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: laravel-configmap
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data-slave
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
