apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-configmap
data:
  APP_ENV: "local"
  DB_CONNECTION: "pgsql"
  DB_HOST: "primary-db-service"
  DB_PORT: "5432"
  DB_DATABASE: "laravel"
  DB_USERNAME: "sysadmin"
  DB_PASSWORD: "neuron_123"
  POSTGRES_HOST: "primary-db-service"
  POSTGRES_DB: "laravel"
  POSTGRES_USER: "sysadmin"
  POSTGRES_PASSWORD: "neuron_123"
  MEMCACHED_HOST: "redis-service"
  REDIS_HOST: "redis-service"
  REDIS_PASSWORD: "neuron_123"
  REDIS_PORT: "6379"
